export const domains = [
  {tld: ".de", answers: ["deutschland", "germany"], difficulty: 1, hints: ["Europa", "Beginnt mit D", "🇩🇪"]},
  {tld: ".com", answers: ["kommerziell", "commercial"], difficulty: 1, hints: ["Allgemein", "Meistgenutzt", "🏢"]},
  {tld: ".org", answers: ["organisation", "organization"], difficulty: 1, hints: ["Gemeinnützig", "Nicht kommerziell", "🏛️"]},
  {tld: ".net", answers: ["netzwerk", "network"], difficulty: 1, hints: ["Technisch", "Internet", "🌐"]},
  {tld: ".uk", answers: ["vereinigtes königreich", "united kingdom", "england", "uk"], difficulty: 1, hints: ["Europa", "Insel", "🇬🇧"]},
  {tld: ".us", answers: ["usa", "vereinigte staaten", "united states", "america"], difficulty: 1, hints: ["Nordamerika", "Stars and Stripes", "🇺🇸"]},
  {tld: ".fr", answers: ["frankreich", "france"], difficulty: 1, hints: ["Europa", "Nachbarland", "🇫🇷"]},
  {tld: ".it", answers: ["italien", "italy"], difficulty: 1, hints: ["Südeuropa", "Pizza", "🇮🇹"]},
  {tld: ".es", answers: ["spanien", "spain"], difficulty: 1, hints: ["Südeuropa", "Flamenco", "🇪🇸"]},
  {tld: ".cn", answers: ["china"], difficulty: 1, hints: ["Asien", "Große Mauer", "🇨🇳"]},
  {tld: ".jp", answers: ["japan"], difficulty: 2, hints: ["Asien", "Inselstaat", "🇯🇵"]},
  {tld: ".ca", answers: ["kanada", "canada"], difficulty: 2, hints: ["Nordamerika", "Ahornblatt", "🇨🇦"]},
  {tld: ".au", answers: ["australien", "australia"], difficulty: 2, hints: ["Ozeanien", "Känguru", "🇦🇺"]},
  {tld: ".ch", answers: ["schweiz", "switzerland"], difficulty: 2, hints: ["Europa", "Neutralität", "🇨🇭"]},
  {tld: ".at", answers: ["österreich", "austria"], difficulty: 2, hints: ["Europa", "Alpen", "🇦🇹"]},
  {tld: ".nl", answers: ["niederlande", "netherlands", "holland"], difficulty: 2, hints: ["Europa", "Windmühlen", "🇳🇱"]},
  {tld: ".ru", answers: ["russland", "russia"], difficulty: 2, hints: ["Eurasien", "Größtes Land", "🇷🇺"]},
  {tld: ".in", answers: ["indien", "india"], difficulty: 2, hints: ["Asien", "Taj Mahal", "🇮🇳"]},
  {tld: ".br", answers: ["brasilien", "brazil"], difficulty: 2, hints: ["Südamerika", "Karneval", "🇧🇷"]},
  {tld: ".gov", answers: ["regierung", "government"], difficulty: 2, hints: ["Staatlich", "Offiziell", "🏛️"]},
  {tld: ".pl", answers: ["polen", "poland"], difficulty: 3, hints: ["Europa", "Osteuropa", "🇵🇱"]},
  {tld: ".se", answers: ["schweden", "sweden"], difficulty: 3, hints: ["Skandinavien", "IKEA", "🇸🇪"]},
  {tld: ".no", answers: ["norwegen", "norway"], difficulty: 3, hints: ["Skandinavien", "Fjorde", "🇳🇴"]},
  {tld: ".dk", answers: ["dänemark", "denmark"], difficulty: 3, hints: ["Skandinavien", "Lego", "🇩🇰"]},
  {tld: ".be", answers: ["belgien", "belgium"], difficulty: 3, hints: ["Europa", "Waffeln", "🇧🇪"]},
  {tld: ".pt", answers: ["portugal"], difficulty: 3, hints: ["Südeuropa", "Atlantikküste", "🇵🇹"]},
  {tld: ".gr", answers: ["griechenland", "greece"], difficulty: 3, hints: ["Antike", "Mittelmeer", "🇬🇷"]},
  {tld: ".ie", answers: ["irland", "ireland"], difficulty: 3, hints: ["Europa", "Grüne Insel", "🇮🇪"]},
  {tld: ".mx", answers: ["mexiko", "mexico"], difficulty: 3, hints: ["Nordamerika", "Sombrero", "🇲🇽"]},
  {tld: ".za", answers: ["südafrika", "south africa"], difficulty: 3, hints: ["Afrika", "Kap der Guten Hoffnung", "🇿🇦"]},
  {tld: ".hr", answers: ["kroatien", "croatia"], difficulty: 4, hints: ["Adria", "Balkan", "🇭🇷"]},
  {tld: ".sg", answers: ["singapur", "singapore"], difficulty: 4, hints: ["Asien", "Stadtstaat", "🇸🇬"]},
  {tld: ".ae", answers: ["vereinigte arabische emirate", "uae", "emirates"], difficulty: 4, hints: ["Naher Osten", "Dubai", "🇦🇪"]},
  {tld: ".kr", answers: ["südkorea", "south korea", "korea"], difficulty: 4, hints: ["Asien", "Technologieland", "🇰🇷"]},
  {tld: ".fi", answers: ["finnland", "finland"], difficulty: 4, hints: ["Skandinavien", "Nokia", "🇫🇮"]},
  {tld: ".cz", answers: ["tschechien", "czech", "czechia"], difficulty: 4, hints: ["Mitteleuropa", "Prag", "🇨🇿"]},
  {tld: ".hu", answers: ["ungarn", "hungary"], difficulty: 4, hints: ["Mitteleuropa", "Budapest", "🇭🇺"]},
  {tld: ".ro", answers: ["rumänien", "romania"], difficulty: 4, hints: ["Osteuropa", "Dracula", "🇷🇴"]},
  {tld: ".ar", answers: ["argentinien", "argentina"], difficulty: 4, hints: ["Südamerika", "Tango", "🇦🇷"]},
  {tld: ".cl", answers: ["chile"], difficulty: 4, hints: ["Südamerika", "Langes Land", "🇨🇱"]},
  {tld: ".mk", answers: ["mazedonien", "north macedonia"], difficulty: 5, hints: ["Balkan", "Ehem. Jugoslawien", "🇲🇰"]},
  {tld: ".vu", answers: ["vanuatu"], difficulty: 5, hints: ["Ozeanien", "Inselstaat", "🇻🇺"]},
  {tld: ".uz", answers: ["usbekistan", "uzbekistan"], difficulty: 5, hints: ["Asien", "Seidenstraße", "🇺🇿"]},
  {tld: ".si", answers: ["slowenien", "slovenia"], difficulty: 5, hints: ["Europa", "Balkan", "🇸🇮"]},
  {tld: ".is", answers: ["island", "iceland"], difficulty: 5, hints: ["Europa", "Vulkane", "🇮🇸"]},
  {tld: ".lu", answers: ["luxemburg", "luxembourg"], difficulty: 5, hints: ["Europa", "Kleinstaat", "🇱🇺"]},
  {tld: ".ee", answers: ["estland", "estonia"], difficulty: 5, hints: ["Baltikum", "Digitales Land", "🇪🇪"]},
  {tld: ".lv", answers: ["lettland", "latvia"], difficulty: 5, hints: ["Baltikum", "Riga", "🇱🇻"]},
  {tld: ".lt", answers: ["litauen", "lithuania"], difficulty: 5, hints: ["Baltikum", "Vilnius", "🇱🇹"]},
  {tld: ".bg", answers: ["bulgarien", "bulgaria"], difficulty: 5, hints: ["Balkan", "Schwarzmeer", "🇧🇬"]},

  // ab hier 150 neue — gleiche Struktur
  {tld: ".sk", answers: ["slowakei", "slovakia"], difficulty: 5, hints: ["Mitteleuropa", "Neben Tschechien", "🇸🇰"]},
  {tld: ".by", answers: ["weißrussland", "belarus"], difficulty: 5, hints: ["Osteuropa", "Neben Polen", "🇧🇾"]},
  {tld: ".ua", answers: ["ukraine"], difficulty: 4, hints: ["Osteuropa", "Kiew", "🇺🇦"]},
  {tld: ".tr", answers: ["türkei", "turkey"], difficulty: 3, hints: ["Europa & Asien", "Istanbul", "🇹🇷"]},
  {tld: ".sa", answers: ["saudi-arabien", "saudi arabia"], difficulty: 4, hints: ["Naher Osten", "Wüste", "🇸🇦"]},
  {tld: ".ir", answers: ["iran"], difficulty: 4, hints: ["Naher Osten", "Persien", "🇮🇷"]},
  {tld: ".iq", answers: ["irak", "iraq"], difficulty: 4, hints: ["Naher Osten", "Bagdad", "🇮🇶"]},
  {tld: ".jo", answers: ["jordanien", "jordan"], difficulty: 5, hints: ["Naher Osten", "Petra", "🇯🇴"]},
  {tld: ".eg", answers: ["ägypten", "egypt"], difficulty: 3, hints: ["Afrika", "Pyramiden", "🇪🇬"]},
  {tld: ".tn", answers: ["tunesien", "tunisia"], difficulty: 4, hints: ["Nordafrika", "Tourismus", "🇹🇳"]},
  {tld: ".dz", answers: ["algerien", "algeria"], difficulty: 4, hints: ["Nordafrika", "Sahara", "🇩🇿"]},
  {tld: ".ma", answers: ["marokko", "morocco"], difficulty: 3, hints: ["Afrika", "Marrakesch", "🇲🇦"]},
  {tld: ".ng", answers: ["nigeria"], difficulty: 4, hints: ["Afrika", "Bevölkerungsreich", "🇳🇬"]},
  {tld: ".ke", answers: ["kenia", "kenya"], difficulty: 4, hints: ["Afrika", "Safari", "🇰🇪"]},
  {tld: ".et", answers: ["äthiopien", "ethiopia"], difficulty: 5, hints: ["Afrika", "Horn von Afrika", "🇪🇹"]},
  {tld: ".gh", answers: ["ghana"], difficulty: 5, hints: ["Westafrika", "Küste", "🇬🇭"]},
  {tld: ".tz", answers: ["tansania", "tanzania"], difficulty: 5, hints: ["Afrika", "Serengeti", "🇹🇿"]},
  {tld: ".ug", answers: ["uganda"], difficulty: 5, hints: ["Afrika", "Neben Kenia", "🇺🇬"]},
  {tld: ".zw", answers: ["simbabwe", "zimbabwe"], difficulty: 5, hints: ["Afrika", "Victoriafälle", "🇿🇼"]},
  {tld: ".mz", answers: ["mosambik", "mozambique"], difficulty: 5, hints: ["Afrika", "Ostküste", "🇲🇿"]},
  {tld: ".na", answers: ["namibia"], difficulty: 5, hints: ["Afrika", "Wüste", "🇳🇦"]},
  {tld: ".bw", answers: ["botswana"], difficulty: 5, hints: ["Afrika", "Okavango-Delta", "🇧🇼"]},
  {tld: ".zm", answers: ["sambia", "zambia"], difficulty: 5, hints: ["Afrika", "Neben Simbabwe", "🇿🇲"]},
  {tld: ".ao", answers: ["angola"], difficulty: 5, hints: ["Afrika", "Öl", "🇦🇴"]},
  {tld: ".cm", answers: ["kamerun", "cameroon"], difficulty: 5, hints: ["Afrika", "Westküste", "🇨🇲"]},
  {tld: ".sn", answers: ["senegal"], difficulty: 5, hints: ["Afrika", "Dakar", "🇸🇳"]},
  {tld: ".ml", answers: ["mali"], difficulty: 5, hints: ["Afrika", "Wüste", "🇲🇱"]},
  {tld: ".bf", answers: ["burkina faso"], difficulty: 5, hints: ["Afrika", "Sahelzone", "🇧🇫"]},
  {tld: ".ne", answers: ["niger"], difficulty: 5, hints: ["Afrika", "Wüste", "🇳🇪"]},
  {tld: ".sd", answers: ["sudan"], difficulty: 5, hints: ["Afrika", "Nil", "🇸🇩"]},
  {tld: ".ly", answers: ["libyen", "libya"], difficulty: 5, hints: ["Nordafrika", "Tripolis", "🇱🇾"]},
  {tld: ".om", answers: ["oman"], difficulty: 5, hints: ["Naher Osten", "Wüste", "🇴🇲"]},
  {tld: ".qa", answers: ["katar", "qatar"], difficulty: 4, hints: ["Naher Osten", "WM 2022", "🇶🇦"]},
  {tld: ".kw", answers: ["kuwait"], difficulty: 4, hints: ["Golfregion", "Ölreich", "🇰🇼"]},
  {tld: ".bh", answers: ["bahrain"], difficulty: 5, hints: ["Golfregion", "Kleinstaat", "🇧🇭"]},
  {tld: ".ye", answers: ["jemen", "yemen"], difficulty: 5, hints: ["Naher Osten", "Krisenland", "🇾🇪"]},
  {tld: ".pk", answers: ["pakistan"], difficulty: 4, hints: ["Asien", "Neben Indien", "🇵🇰"]},
  {tld: ".bd", answers: ["bangladesch", "bangladesh"], difficulty: 4, hints: ["Asien", "Dicht besiedelt", "🇧🇩"]},
  {tld: ".np", answers: ["nepal"], difficulty: 5, hints: ["Asien", "Himalaya", "🇳🇵"]},
  {tld: ".bt", answers: ["bhutan"], difficulty: 5, hints: ["Asien", "Kleines Königreich", "🇧🇹"]},
  {tld: ".lk", answers: ["sri lanka"], difficulty: 5, hints: ["Asien", "Inselstaat", "🇱🇰"]},
  {tld: ".mm", answers: ["myanmar", "burma"], difficulty: 5, hints: ["Südostasien", "Yangon", "🇲🇲"]},
  {tld: ".th", answers: ["thailand"], difficulty: 3, hints: ["Asien", "Bangkok", "🇹🇭"]},
  {tld: ".vn", answers: ["vietnam"], difficulty: 3, hints: ["Asien", "Pho", "🇻🇳"]},
  {tld: ".ph", answers: ["philippinen", "philippines"], difficulty: 3, hints: ["Asien", "Inselstaat", "🇵🇭"]},
  {tld: ".id", answers: ["indonesien", "indonesia"], difficulty: 3, hints: ["Asien", "1000 Inseln", "🇮🇩"]},
  {tld: ".my", answers: ["malaysia"], difficulty: 4, hints: ["Asien", "Kuala Lumpur", "🇲🇾"]},
  {tld: ".la", answers: ["laos"], difficulty: 5, hints: ["Südostasien", "Landlocked", "🇱🇦"]},
  {tld: ".kh", answers: ["kambodscha", "cambodia"], difficulty: 5, hints: ["Asien", "Angkor Wat", "🇰🇭"]},
  {tld: ".mn", answers: ["mongolei", "mongolia"], difficulty: 5, hints: ["Asien", "Steppe", "🇲🇳"]},
  {tld: ".kg", answers: ["kirgisistan", "kyrgyzstan"], difficulty: 5, hints: ["Asien", "Gebirge", "🇰🇬"]},
  {tld: ".tj", answers: ["tadschikistan", "tajikistan"], difficulty: 5, hints: ["Asien", "Pamir-Gebirge", "🇹🇯"]},
  {tld: ".tm", answers: ["turkmenistan"], difficulty: 5, hints: ["Asien", "Wüste", "🇹🇲"]},
  {tld: ".af", answers: ["afghanistan"], difficulty: 5, hints: ["Asien", "Gebirge", "🇦🇫"]},
  {tld: ".ge", answers: ["georgien", "georgia"], difficulty: 5, hints: ["Kaukasus", "Tiflis", "🇬🇪"]},
  {tld: ".am", answers: ["armenien", "armenia"], difficulty: 5, hints: ["Kaukasus", "Berge", "🇦🇲"]},
  {tld: ".az", answers: ["aserbaidschan", "azerbaijan"], difficulty: 5, hints: ["Kaukasus", "Baku", "🇦🇿"]},
  {tld: ".il", answers: ["israel"], difficulty: 4, hints: ["Naher Osten", "Jerusalem", "🇮🇱"]},
  {tld: ".ps", answers: ["palästina", "palestine"], difficulty: 5, hints: ["Naher Osten", "Westjordanland", "🇵🇸"]},
  {tld: ".jo", answers: ["jordanien"], difficulty: 5, hints: ["Naher Osten", "Totes Meer", "🇯🇴"]},
  {tld: ".lb", answers: ["libanon", "lebanon"], difficulty: 5, hints: ["Naher Osten", "Beirut", "🇱🇧"]},
  {tld: ".cy", answers: ["zypern", "cyprus"], difficulty: 4, hints: ["Insel", "Mittelmeer", "🇨🇾"]},
  {tld: ".mt", answers: ["malta"], difficulty: 4, hints: ["Mittelmeer", "Klein aber wichtig", "🇲🇹"]},
  {tld: ".sm", answers: ["san marino"], difficulty: 5, hints: ["Europa", "Kleinstaat", "🇸🇲"]},
  {tld: ".mc", answers: ["monaco"], difficulty: 4, hints: ["Europa", "Reich", "🇲🇨"]},
  {tld: ".ad", answers: ["andorra"], difficulty: 5, hints: ["Pyrenäen", "Zwischen Frankreich und Spanien", "🇦🇩"]},
  {tld: ".li", answers: ["liechtenstein"], difficulty: 5, hints: ["Europa", "Kleinstaat", "🇱🇮"]},
  {tld: ".va", answers: ["vatikan", "vatican"], difficulty: 5, hints: ["Kleinstaat", "Papst", "🇻🇦"]},
  {tld: ".al", answers: ["albanien", "albania"], difficulty: 4, hints: ["Balkan", "Tirana", "🇦🇱"]},
  {tld: ".rs", answers: ["serbien", "serbia"], difficulty: 4, hints: ["Balkan", "Belgrad", "🇷🇸"]},
  {tld: ".ba", answers: ["bosnien", "bosnia"], difficulty: 4, hints: ["Balkan", "Sarajevo", "🇧🇦"]},
  {tld: ".me", answers: ["montenegro"], difficulty: 4, hints: ["Balkan", "Adria", "🇲🇪"]},
  {tld: ".xk", answers: ["kosovo"], difficulty: 5, hints: ["Balkan", "Umstritten", "🇽🇰"]},
  {tld: ".md", answers: ["moldawien", "moldova"], difficulty: 5, hints: ["Osteuropa", "Kleines Land", "🇲🇩"]},
  {tld: ".ge", answers: ["georgien", "georgia"], difficulty: 5, hints: ["Kaukasus", "Tiflis", "🇬🇪"]},
  {tld: ".kz", answers: ["kasachstan", "kazakhstan"], difficulty: 4, hints: ["Asien", "Steppe", "🇰🇿"]},
  {tld: ".uz", answers: ["usbekistan"], difficulty: 5, hints: ["Asien", "Seidenstraße", "🇺🇿"]},
  {tld: ".tj", answers: ["tadschikistan"], difficulty: 5, hints: ["Gebirge", "Asien", "🇹🇯"]},
  {tld: ".tm", answers: ["turkmenistan"], difficulty: 5, hints: ["Wüste", "Asien", "🇹🇲"]},
  {tld: ".kg", answers: ["kirgisistan"], difficulty: 5, hints: ["Gebirge", "Asien", "🇰🇬"]},
  {tld: ".mn", answers: ["mongolei"], difficulty: 5, hints: ["Steppe", "Asien", "🇲🇳"]},
  {tld: ".nz", answers: ["neuseeland", "new zealand"], difficulty: 3, hints: ["Ozeanien", "Herr der Ringe", "🇳🇿"]},
  {tld: ".fj", answers: ["fidschi", "fiji"], difficulty: 5, hints: ["Pazifik", "Inselstaat", "🇫🇯"]},
  {tld: ".pg", answers: ["papua-neuguinea", "papua new guinea"], difficulty: 5, hints: ["Ozeanien", "Neben Australien", "🇵🇬"]},
  {tld: ".sb", answers: ["salomonen", "solomon islands"], difficulty: 5, hints: ["Ozeanien", "Inselgruppe", "🇸🇧"]},
  {tld: ".to", answers: ["tonga"], difficulty: 5, hints: ["Pazifik", "Königreich", "🇹🇴"]},
  {tld: ".ws", answers: ["samoa"], difficulty: 5, hints: ["Pazifik", "Polynesien", "🇼🇸"]},
  {tld: ".tv", answers: ["tuvalu"], difficulty: 5, hints: ["Pazifik", "Klein & Internet-TLD", "🇹🇻"]},
  {tld: ".nr", answers: ["nauru"], difficulty: 5, hints: ["Pazifik", "Kleinstaat", "🇳🇷"]},
  {tld: ".ck", answers: ["cookinseln", "cook islands"], difficulty: 5, hints: ["Pazifik", "Inselgruppe", "🇨🇰"]},
  {tld: ".pf", answers: ["französisch-polynesien", "french polynesia"], difficulty: 5, hints: ["Pazifik", "Tahiti", "🇵🇫"]},
  {tld: ".nc", answers: ["neukaledonien", "new caledonia"], difficulty: 5, hints: ["Pazifik", "Französisch", "🇳🇨"]},
  {tld: ".gl", answers: ["grönland", "greenland"], difficulty: 4, hints: ["Arktis", "Eis", "🇬🇱"]},
  {tld: ".fo", answers: ["färöer", "faroe islands"], difficulty: 5, hints: ["Nordatlantik", "Autonom", "🇫🇴"]},
  {tld: ".gi", answers: ["gibraltar"], difficulty: 5, hints: ["Südspanien", "Britisch", "🇬🇮"]},
  {tld: ".gg", answers: ["guernsey"], difficulty: 5, hints: ["Kanalinseln", "Britisch", "🇬🇬"]},
  {tld: ".je", answers: ["jersey"], difficulty: 5, hints: ["Kanalinseln", "Steueroase", "🇯🇪"]},
  {tld: ".im", answers: ["isle of man"], difficulty: 5, hints: ["Britisch", "Zwischen England & Irland", "🇮🇲"]},
  {tld: ".cx", answers: ["weihnachtsinsel", "christmas island"], difficulty: 5, hints: ["Ozeanien", "Australien", "🎄"]},
  {tld: ".io", answers: ["britisches territorium im indischen ozean"], difficulty: 5, hints: ["Britisch", "Indischer Ozean", "🇮🇴"]},
  {tld: ".sh", answers: ["st. helena"], difficulty: 5, hints: ["Atlantik", "Napoleon", "🇸🇭"]},
  {tld: ".fk", answers: ["falklandinseln", "falklands"], difficulty: 5, hints: ["Südamerika", "Britisch", "🇫🇰"]},
  {tld: ".bm", answers: ["bermuda"], difficulty: 5, hints: ["Atlantik", "Dreieck", "🇧🇲"]},
  {tld: ".ky", answers: ["cayman islands"], difficulty: 5, hints: ["Karibik", "Finanzplatz", "🇰🇾"]},
  {tld: ".bs", answers: ["bahamas"], difficulty: 4, hints: ["Karibik", "Inseln", "🇧🇸"]},
  {tld: ".bb", answers: ["barbados"], difficulty: 5, hints: ["Karibik", "Rihanna", "🇧🇧"]},
  {tld: ".tt", answers: ["trinidad und tobago"], difficulty: 5, hints: ["Karibik", "Doppelinsel", "🇹🇹"]},
  {tld: ".jm", answers: ["jamaika", "jamaica"], difficulty: 4, hints: ["Karibik", "Reggae", "🇯🇲"]},
  {tld: ".cu", answers: ["kuba", "cuba"], difficulty: 4, hints: ["Karibik", "Havanna", "🇨🇺"]},
  {tld: ".do", answers: ["dominikanische republik"], difficulty: 4, hints: ["Karibik", "Tourismus", "🇩🇴"]},
  {tld: ".ht", answers: ["haiti"], difficulty: 5, hints: ["Karibik", "Armes Land", "🇭🇹"]},
  {tld: ".cr", answers: ["costa rica"], difficulty: 4, hints: ["Mittelamerika", "Natur", "🇨🇷"]},
  {tld: ".pa", answers: ["panama"], difficulty: 4, hints: ["Mittelamerika", "Kanal", "🇵🇦"]},
  {tld: ".ni", answers: ["nicaragua"], difficulty: 5, hints: ["Mittelamerika", "Managua", "🇳🇮"]},
  {tld: ".hn", answers: ["honduras"], difficulty: 5, hints: ["Mittelamerika", "Tegucigalpa", "🇭🇳"]},
  {tld: ".sv", answers: ["el salvador"], difficulty: 5, hints: ["Mittelamerika", "Bitcoin", "🇸🇻"]},
  {tld: ".gt", answers: ["guatemala"], difficulty: 4, hints: ["Mittelamerika", "Maya-Ruinen", "🇬🇹"]},
  {tld: ".ec", answers: ["ecuador"], difficulty: 4, hints: ["Südamerika", "Äquator", "🇪🇨"]},
  {tld: ".pe", answers: ["peru"], difficulty: 4, hints: ["Südamerika", "Machu Picchu", "🇵🇪"]},
  {tld: ".co", answers: ["kolumbien", "colombia"], difficulty: 4, hints: ["Südamerika", "Kaffee", "🇨🇴"]},
  {tld: ".ve", answers: ["venezuela"], difficulty: 4, hints: ["Südamerika", "Erdöl", "🇻🇪"]}
];
